services:
  - type: web
    name: laravel-react-portfolio
    env: docker
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: LOG_CHANNEL
        value: stderr
      - key: AUTORUN_ENABLED
        value: "true"
      - key: AUTORUN_LARAVEL_MIGRATION
        value: "true"